float64 allowable_cost_per_observation
sensor_msgs/RegionOfInterest roi # leave blank to use whole image
geometry_msgs/Pose initial_pose
---
float64 cost_per_observation
geometry_msgs/Pose final_pose
bool success
