# Define the goal
string instructions
uint32 target_type  
string image_topic
uint32 roi_min_x
uint32 roi_min_y
uint32 roi_max_x
uint32 roi_max_y
uint32 grid_rows
uint32 grid_cols
---
# Define the result
uint32 result  # just a placeholder
---
# Define a feedback message
float32 percent_complete